{
  parserClass="com.neptune.jagintellij.parser.JagConfigParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JagConfig"
  psiImplClassSuffix="Impl"
  psiPackage="com.neptune.jagintellij.psi"
  psiImplPackage="com.neptune.jagintellij.psi.impl"

  elementTypeHolderClass="com.neptune.jagintellij.psi.JagConfigTypes"
  elementTypeClass="com.neptune.jagintellij.psi.JagConfigElementType"
  tokenTypeClass="com.neptune.jagintellij.psi.JagConfigTokenType"

  tokens = [
    IDENTIFIER = "regexp:[a-zA-Z_]([a-zA-Z_0-9])*"
    SEPARATOR = "="
    DIGIT = "regexp:\d"
  ]
}

file ::= file_item*

private file_item ::= {
    header
    (property|COMMENT|CRLF)*
}

header ::= "[" + IDENTIFIER + "]"

property ::= (KEY? SEPARATOR DIGIT+) | KEY
